wandb_version: 1

learning_rate:
  desc: null
  value: 5.0e-05
architecture:
  desc: null
  value: SE_Net_test
dataset:
  desc: null
  value: Faces
epochs:
  desc: null
  value: 40
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682647984.613483
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 2
      - 16
      - 23
      4: 3.9.12
      5: 0.15.0
      8:
      - 3
      - 5
